### ISSUE TITLE
Typo in Driver Usage section

### ISSUE THREAD

**Issue by cbogdon** [clearpath-docs/spot-ros-sphinx-tutorials#6]
"Spot ROS Driver Usuage" should be "Spot ROS River Usage"  

![image](https://user-images.githubusercontent.com/13753182/94052475-03013d00-fda7-11ea-8ead-546ff93eb1ec.png)

**Comment by civerachb-cpr** [comment]
Fixed in https://github.com/clearpath-docs/spot-ros-sphinx-tutorials/pull/7
